export const REQUEST_SET_MISSIONS = 'REQUEST_SET_MISSIONS';
export const SUCCESS_SET_MISSIONS = 'SUCCESS_SET_MISSIONS';
export const FAILURE_SET_MISSIONS = 'FAILURE_SET_MISSIONS';

export const REQUEST_SET_HISTORY = 'REQUEST_SET_HISTORY';
export const SUCCESS_SET_HISTORY = 'SUCCESS_SET_HISTORY';
export const FAILURE_SET_HISTORY = 'FAILURE_SET_HISTORY';

export const REQUEST_SET_USER = 'REQUEST_SET_USER';
export const SUCCESS_SET_USER = 'SUCCESS_SET_USER';
export const FAILURE_SET_USER = 'FAILURE_SET_USER';
export const RESET_USER = 'RESET_USER';

export const REQUEST_SET_AVAT = 'REQUEST_SET_AVAT';
export const SUCCESS_SET_AVAT = 'SUCCESS_SET_AVAT';
export const FAILURE_SET_AVAT = 'FAILURE_SET_AVAT';
export const RESET_AVAT = 'RESET_AVAT';

export const REQUEST_SET_PROF = 'REQUEST_SET_PROF';
export const SUCCESS_SET_PROF = 'SUCCESS_SET_PROF';
export const FAILURE_SET_PROF = 'FAILURE_SET_PROF';
export const RESET_PROF = 'RESET_PROF';